spring:
  thymeleaf:
    prefix:
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: 'false'
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
